function indexView(){
    return '<div class="container" style="margin-top: 50px">'
    +'        <div class="card card-container" style="width: 192px">'
    +'            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />'
    +'            <p id="profile-name" class="profile-name-card"></p>'
    +'            <form class="form-signin">'
    +'                <span id="reauth-email" class="reauth-email"></span>'
    +'                <input type="text" id="userId" class="form-control" placeholder="ID" required autofocus>'
    +'                <input type="password" id="pass" class="form-control" placeholder="Password" required>'
    +'                <div id="remember" class="checkbox">'
    +'                    <label>'
    +'                        <input type="checkbox" value="remember-me"> Remember me'
    +'                    </label>'
    +'                </div>'
    +'                <button id="login" class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>'
    +'                <button id="register" class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Register</button>'
    +'            </form>'
    +'            <a href="#" class="forgot-password">'
    +'                Forgot the password?'
    +'            </a>'
    +'            <a id="board" href="#"><button class="btn btn-lg btn-primary btn-block btn-signin" type="submit" style="margin-top: 30px;">Go Board</button></a>'
    +'        </div>'
    +'    </div>';
}
function boardView(){
    return '<div style="padding: 50px"></div>'
    +'<div style="width:100%">'
    +'<div style="margin: 0 auto; text-align:center; width: 700px">'
    +'	<table id="board_list" class="table table-hover">'
    +'		<tr>'
    +'			<td colspan="5">총 게시글 수 : <b id="count"></b>건</td>'
    +'		</tr>'
    +'		<tr>'
    +'			<td>Seq</td>'
    +'			<td>사용자 ID</td>'
    +'			<td>제목</td>'
    +'			<td>작성일</td>'
    +'			<td>카운트</td>'
    +'		</tr>'		
    +'	</table>'
    +'	<nav aria-label="Page navigation">'
    +'	  <ul id="pagination" class="pagination">'
    +'	  </ul>'
    +'	</nav>'
    +'  <div style="text-align: right"><a id="write" href="#"><input type="button" value="글쓰기" style="background: white;  margin-bottom: 70px;"/></a></div>'
    +'</div>'
    +'</div>';
}

function boardListContent(i){
    return '<tr>'
    +'			<td id="seq'+i+'" class="seq">1</td>'
    +'			<td id="userid'+i+'" class="userid">babungv</td>'
    +'			<td><a id="title'+i+'" class="title" href="javascript:void(0)">title1</a></td>'
    +'			<td id="date'+i+'" class="regdate">2017-06-05</td>'
    +'			<td id="count'+i+'" class="readcount">0</td>'
    +'		</tr>';
}
function prevBlock(){
    return '<li id="previous">'
    +'	      <a id="prevBlock" href="#" aria-label="Previous">'
    +'	        <span aria-hidden="true">&laquo;</span>'
    +'	      </a>'
    +'	    </li>';
}
function nextBlock(){
    return '<li id="next">'
    +'	      <a id="nextBlock" href="#" aria-label="Next">'
    +'	        <span aria-hidden="true">&raquo;</span>'
    +'	      </a>'
    +'	    </li>';
}
function writeView(){
    return '<div style="padding: 50px"></div>'
    +'<div style="width:100%">'
    +'	<div style="margin: 0 auto; width: 339px">'
    +'		<ul class="list-group">'
    +'  			<li class="list-group-item list-group-item-success"><input id="title" type="text" placeholder="제목"/></li>'
    +'  			<li class="list-group-item list-group-item-success"><textarea name="" id="content" cols="40" rows="10" placeholder="내용"></textarea></li>'
    +'  			<li class="list-group-item list-group-item-success"><a id="cancel" href="javascript:void(0)"><input type="button" value="취소"/></a><a id="write" href="javascript:void(0)"><input type="button" value="글쓰기"/></a></li>'
    +'		</ul>'
    +'	</div>'
    +'</div>'
}
function registerView(){
    return 	'<div class="container" style="margin-top: 50px;">'
    +'    <div class="row centered-form">'
    +'    <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">'
    +'    	<div class="panel panel-default">'
    +'    		<div class="panel-heading">'
	+'		    		<h3 class="panel-title">Register Form</h3>'
	+'		 			</div>'
	+'		 			<div class="panel-body">'
	+'		    		<form role="form">'
	+'		    			<div class="row">'
	+'		    				<div class="col-xs-6 col-sm-6 col-md-6">'
	+'		    					<div class="form-group">'
	+'		                			<input type="text" name="userId" id="userId" class="form-control input-sm" placeholder="ID">'
	+'		    					</div>'
	+'		    				</div>'
	+'		    				<div class="col-xs-6 col-sm-6 col-md-6">'
	+'		    					<div class="form-group">'
	+'		    						<input type="text" name="age" id="age" class="form-control input-sm" placeholder="Age">'
	+'		    					</div>'
	+'		    				</div>'
	+'		    			</div>'
	+'		    			<div class="form-group">'
	+'		    				<input type="text" name="phone" id="phone" class="form-control input-sm" placeholder="Phone Number">'
	+'		    			</div>'
	+'		    			<div class="row">'
	+'		    				<div class="col-xs-6 col-sm-6 col-md-6">'
	+'		    					<div class="form-group">'
	+'		    						<input type="password" name="password" id="password" class="form-control input-sm" placeholder="Password">'
	+'		    					</div>'
	+'		    				</div>'
	+'		    				<div class="col-xs-6 col-sm-6 col-md-6">'
	+'		    					<div class="form-group">'
	+'		    						<input type="password" name="password_confirmation" id="password_confirmation" class="form-control input-sm" placeholder="Confirm Password">'
	+'		    					</div>'
	+'		    				</div>'
	+'		    			</div>'
	+'		    			<a id="user_register" href="javascript:void(0)"><input type="button" value="Register" class="btn btn-info btn-block"></a>'
	+'		    		</form>'
	+'		    	</div>'
	+'   		</div>'
    +'		</div>'
    +'	</div>'
    +'</div>';
}